# Generated by Django 4.2.15 on 2024-09-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRecord',
        ),
    ]
