# Generated by Django 4.2.15 on 2024-08-29 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_order_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='transaction',
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.order'),
        ),
    ]
