# Generated by Django 4.2.15 on 2024-08-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_transactions_remove_order_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_detail', to='products.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.transaction'),
        ),
    ]
