# Generated by Django 4.2.15 on 2024-09-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_transaction_delete_transactions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
